import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <nav>
          <Link href="/">홈 </Link>
          <Link href="/product/list">상품 </Link>
          <Link href="/theme">테마목록 </Link>
          <Link href="/review">리뷰</Link>
          <Link href="/auth/login">로그인</Link>
          <Link href="/auth/signup">회원가입</Link>
          <Link href="/personal">마이페이지</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
