export const CATEGORY_OPTIONS = [
  { id: 1, code: "CANDLE", label: "캔들/디퓨저" },
  { id: 2, code: "SOAP", label: "비누/화장품" },
  { id: 3, code: "LEATHER", label: "가죽공예" },
  { id: 4, code: "WOOD", label: "목공/가구" },
  { id: 5, code: "CERAMIC", label: "도자기/세라믹" },
  { id: 6, code: "JEWELRY", label: "금속/주얼리" },
  { id: 7, code: "FABRIC", label: "섬유/자수" },
  { id: 8, code: "DRAWING", label: "드로잉/일러스트" },
  { id: 9, code: "FLOWER", label: "플라워/식물" },
  { id: 10, code: "PAPER", label: "종이공예/북아트" },
  { id: 11, code: "RESIN", label: "레진/몰드공예" },
  { id: 12, code: "AROMA", label: "향/아로마" },
  { id: 13, code: "KIDS", label: "키즈/DIY 키트" },
  { id: 14, code: "PET", label: "반려동물용품" },
  { id: 15, code: "GLASS", label: "유리공예" },
  { id: 16, code: "DYE", label: "천연염색/직조" },
  { id: 17, code: "MINIATURE", label: "미니어처/디오라마" },
  { id: 18, code: "UPCYCLE", label: "업사이클링" },
  { id: 19, code: "ORIGAMI", label: "종이접기/오리가미" },
  { id: 20, code: "LIGHT", label: "조명/무드등" },
  { id: 21, code: "REST", label: "휴식용품" },
  { id: 22, code: "FOOD", label: "수제간식/천연식품" },
  { id: 23, code: "DIGITAL", label: "디지털아트/프린팅" },
  { id: 24, code: "TRADITIONAL", label: "전통공예" },
  { id: 25, code: "DIY_ELECTRONIC", label: "DIY 전자키트" },
  { id: 26, code: "MOOD", label: "감성소품" },
  { id: 27, code: "MINI", label: "스몰굿즈" },
];
